### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by Rintan** [PocketMine/SimpleAuth#106]
Warning: Illegal offset type in phar://C:/Users/Broadleaf/Desktop/Minecraft/Genisys/plugins/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask.php on line 42
Warning: Illegal offset type in unset in phar://C:/Users/Broadleaf/Desktop/Minecraft/Genisys/plugins/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask.php on line 46

This issues occured in PocketMine-MP for PHP7.

**Comment by MKBandzz** [comment]
This isnt really a big issue. It just means that the team didnt update it to the new name of "ShowMessageTask". i see it as an advantage, because it shows when a user logs in!
