### ISSUE TITLE
you do not have permission to use this command???

### ISSUE THREAD

**Issue by Bidou0418** [PocketMine/SimpleAuth#107]
Everytime i install the latest SimpleAuth and login, i try to register as indicated, but i get this message;
You do not have permission to use this command
I also noticed that the time limit for login in or registering doesnt function either.

**Comment by Bidou0418** [comment]
anyone?

**Comment by Bidou0418** [comment]
did they or he take a vacation?

**Comment by Bidou0418** [comment]
Try this plugin instead. it works quite well for me
PEMapModder/HereAuth

**Comment by ghost** [comment]
Install SimpleAuthHelper plugin :)
