### ISSUE TITLE
SimpleAuth No Longer loads with latest version of Elywing

### ISSUE THREAD

**Issue by HiggsInc** [PocketMine/SimpleAuth#116]
Hi,

Tried to update my server with the latest release of Elywing
https://github.com/H4PM/Elywing/tree/b5d374f19240baf52bfe4aed1514c4d4c0552cc8

Ive discovered that SimpleAuth v1.7.2 no longer works. I've rolled back to a previous server version where the plugin now functions.

Please advise?

**Comment by Sandertv** [comment]
I don't know why you'd think SimpleAuth for PocketMine would be able to fix an issue from Elywing...

**Comment by HiggsInc** [comment]
I agree. At the time of when I lodged this issue, simpleauth had stopped working as their devs were rolling out new releases. Months have gone by and the plugin works perfectly fine now. I've moved away from Elywing for a much more stable pocketmine

**Comment by Sandertv** [comment]
Good to hear! Anyways, if you search a newer version, try the updated one on poggit.pmmp.io.

**Comment by HiggsInc** [comment]
Thanks mate, will do!
