### ISSUE TITLE
OPs cant use /login nor /register

### ISSUE THREAD

**Issue by iJoshuaHD** [PocketMine/SimpleAuth#28]
As what the title says, OPs cant use these commands. i have tested these on a vanilla server without any plugins, just SimpleAuth latest build/version.

I have asked other few Server Operators or Owners that they have the same problem.

**Comment by cloud9350** [comment]
It is a random error. Reboot the server after you delete all the plug-in after installing a fully functional again SimpleAuth.

**Comment by PEMapModder** [comment]
Are the config file**s** completely generated by the latest version of the plugin?

**Comment by iJoshuaHD** [comment]
@cloud9350 no its not.

**Comment by cloud9350** [comment]
@iJoshuaHD Please try the download again.
http://forums.pocketmine.net/plugins/simpleauth.4/

**Comment by iJoshuaHD** [comment]
@cloud9350 i know what im doing. the problem is with the plugin.yml and figured it out last year a few days i created this issue.

**Comment by PEMapModder** [comment]
Just delete the old files.
