### ISSUE TITLE
Login/Register

### ISSUE THREAD

**Issue by Drumpit** [PocketMine/SimpleAuth#52]
PLease make a Update! It says: "You don`t have permission to do that!"
Please fix it!

**Comment by Creeperface01** [comment]
i have same problem. I'm OP but i haven't permissions -,-

**Comment by MinerGirl98** [comment]
I'm having the same problem it says you must register. Then when I try to it says you  don't  have  permission. please help me.

**Comment by shoghicp** [comment]
This is a problem on your setup.

**Comment by MinerGirl98** [comment]
Hi, ok thank you. I'm sorry I never had a server before and I'm trying to make one for the community I work for and I'm lost. Lol. I watched videos and read a lot of articles on the website. I'll figure it out. I haven't beenon there for a while. 
Thanks again. 

Sent on the new Sprint Network from my Samsung Galaxy S®4.

<div>-------- Original message --------</div><div>From: Shoghi Cervantes <notifications@github.com> </div><div>Date:05/23/2015  5:21 PM  (GMT-05:00) </div><div>To: PocketMine/SimpleAuth <SimpleAuth@noreply.github.com> </div><div>Cc: MinerGirl98 <sthomas795@yahoo.com> </div><div>Subject: Re: [SimpleAuth] Login/Register (#52) </div><div>
</div>This is a problem on your setup.

**Comment by Bidou0418** [comment]
fix the app.......
no permission to login
wtf
pass on development
or tell us how to fix pêrmisxsions
