### ISSUE TITLE
Encrypting of passwords

### ISSUE THREAD

**Issue by AndreyNazarchuk** [PocketMine/SimpleAuth#54]
I I deleted everything after line 400 in SimpleAuth.php, would it stop encrypting passwords?
Thanks

**Comment by shoghicp** [comment]
Passwords must be hashed. What you are trying to do is soy on the user passwords. Maybe to use them on other servers?

**Comment by AndreyNazarchuk** [comment]
Why would I do that if i am the owner of the server?

**Comment by Gamecrafter** [comment]
I believe that taking up more disk space is better than being openly hacked. Hashing is actually a more secure way for storing passwords. If you didn't hash it, hackers would get the password the moment they get it.

**Comment by AndreyNazarchuk** [comment]
OK, I get it, can other servers I own connected to the same database read them?

**Comment by shoghicp** [comment]
SimpleAuth supports a MySQL backend so you can share the user database (password are still hashed, as per industry standards recommend)

**Comment by shoghicp** [comment]
SimpleAuth supports a MySQL backend so you can share the user database (password are still hashed, as per industry standards recommend)

**Comment by PEMapModder** [comment]
And if you are using YAML provider, there shouldn't be a problem to share the same database if you modify the plugin data path of PocketMine when you start the server.

**Comment by AndreyNazarchuk** [comment]
Its possible to have multiple servers connect to yaml?
