### ISSUE TITLE
SimpleAuth Permission

### ISSUE THREAD

**Issue by TheEpicCooldeal** [PocketMine/SimpleAuth#62]
In your "plugin.yml" file there is the "simpleauth" permission which is given to any OP by default what players do on my server they join with my name and since im OP I have that permission so they are able to chat and move and they did not even login. Please set it to "false"

permissions:
 simpleauth:
  default: op
  description: "Allows using everything SimpleAuth has"
  children:
   simpleauth.chat:
    description: "Allows using the chat while not being authenticated"
    default: false
   simpleauth.move:
    description: "Allows moving while not being authenticated"
    default: false
   simpleauth.lastid:
    description: "Allows authenticating using the last id when enabled in the config"
    default: true
   simpleauth.command:
    description: "Allows using SimpleAuth commands"
    default: true
    children:
     simpleauth.command.register:
      description: "Allows registering an account"
      default: true
     simpleauth.command.login:
      description: "Allows logging into an account"
      default: true

**Comment by shoghicp** [comment]
The children are set to false - that is only for other permissions

**Comment by TheEpicCooldeal** [comment]
I know that the children are set to false but I still have the permission
