### ISSUE TITLE
Pocketmine 1.6

### ISSUE THREAD

**Issue by Bamuel** [PocketMine/SimpleAuth#87]
I [Server thread/WARNING]: RuntimeException: "Illegal offset type in unset" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 46

Get spammed this

**Comment by HotFireyDeath** [comment]
Use SimpleAuthHelper http://forums.pocketmine.net/plugins/simpleauthhelper.1112/

It should fix this issue.
